### ISSUE TITLE
File name extension should be ttf not otf

### ISSUE THREAD

**Issue by kenmcd** [Aaron-212/InterNumeric#1]
The v1.002.(2024-03-31).release variable file is named `InterNumeric[wght,RDNS].otf`
But it does have TT outlines and should be `.ttf`.

Windows 10 does not like `otf` CFF variable fonts.
So I was a bit wary about this font, and checked it in OTM and FontLab.
It is actually a normal TTF variable font.

To prevent user confusion, and concern, please change the file extension to `.ttf`.

**Comment by Aaron-212** [comment]
Thank you! Fixed in 1.003.
